source/html/sponsor/index.html
=> Fix path to pdf

source/styles/main.scss
Reverts HackIllinois/site-2018#12
=> Revert "Hyperlink styling"

source/components/about/about.jsx, source/components/faq/faq.jsx, source/components/home/home.js
=> Updated copy and move back to V1.2

package.json, source/html/index.html, webpack.config.js
=> Revert "Version Build Files (WIP)"

package.json, source/html/index.html, webpack.config.js
=> Revert "Revert "Version Build Files (WIP)""

.travis.yml
=> Set apple-app-site-association `Content-Type`

.gitignore, source/components/auth/mobile.js, source/html/auth/mobile/index.html, source/index.jsx
=> Added native app redirect endpoint

source/components/register/registerFieldsConfig.js, source/components/registerEssay/registerEssay.js
=> Registration Questions Copy Changes

package-lock.json, source/components/register/register.scss, source/components/register/registerFieldsConfig.js
=> Fixed placeholder text and background color issues

source/components/register/register.js, source/components/register/registerHelper.js
Small spacing and PUT vs. POST fix for resume.
=> Minor Registration Fixes

source/components/countdown/countdown.scss, source/components/faq/faq.jsx, source/components/faq/faq.scss
- Fixes countdown on mobile
- Fixes FAQ on mobile
=> Mobile Site Fixes

source/components/error/error.scss, source/components/registerStart/registerStart.scss
Fixes a bug where the background image would not load on the site.
=> Fixes background

source/components/error/error.scss, source/components/home/home.scss, source/components/registerStart/registerStart.scss
Shows both the background image & the entire color on the /error and /start pages.
=> Fix background issues

source/components/faq/faq.scss
- Fixes too small of FAQ padding on desktop.
=> Fix FAQ Padding

source/components/registerStart/registerStart.js
This reorders the items on `/start` so that it is more intuitive.
=> Reorder Start

.travis.yml, scripts/invalidate.sh
This PR makes it so that travis auto-deploys to the test S3 bucket.
=> Travis staging

.travis.yml, config.js, source/components/auth/auth.js, source/components/auth/mobile.js, source/components/register/registerHelper.js, source/components/registerStart/registerStart.js
Reverts HackIllinois/site-2018#87
=> Revert "Config file for api"

.travis.yml, config.js, source/components/auth/auth.js, source/components/auth/mobile.js, source/components/register/registerHelper.js, source/components/registerStart/registerStart.js
=> Deploy Staging

.travis.yml, config.js, package.json, source/components/auth/auth.js, source/components/auth/mobile.js, source/components/register/registerHelper.js, source/components/registerStart/registerStart.js
Reverts HackIllinois/site-2018#98
=> Revert "Revert "Config file for api""

.travis.yml, config.js, package.json, source/components/auth/auth.js, source/components/auth/mobile.js, source/components/register/registerHelper.js, source/components/registerStart/registerStart.js
Reverts HackIllinois/site-2018#102
=> Revert "Config file"

source/components/registerEssay/registerEssay.js, source/components/registerStart/registerStart.js
Essay page is messed up due to the wrong css tag.
Login button opens new page.
=> Essay page and login button fix

source/components/countdown/countdown.jsx
=> Update countdown destination

source/components/home/home.scss
=> Register button location change

source/components/dayOfLayout/dayOfLayout.js, source/components/mentorship/mentorship.js, source/html/pdf_schedule/index.html, source/index.js
Mentorships to mentors and delete extra route
=>  Mentorships to mentors

source/components/home/home.js, source/components/home/home.scss, source/index.js
Change schedule to day of and kill animation
=> Change schedule to day of

source/components/travel/travelConfig.js
=> Fix bus schedule

source/components/home/home.scss, source/components/schedule/scheduleConfig.js
=> Schedule fix

source/components/countdown/countdown.jsx, source/components/dashboard/dashboardClock.js
=> Countdown fix

source/components/prizes/prizesConfig.js
=> add US ignite prize

source/components/faq/faq.jsx
=> CoC to main page

source/components/home/home.js
Noticed there's not yet a submissions link on the site. This PR replaces the rsvp button with one for the Devpost.
=> Add submissions link to home
